### ISSUE TITLE
`lua_Reader` is not set to correct specs.

### ISSUE THREAD

**Issue by ZILtoid1991** [BindBC/bindbc-lua#13]
While according to official specifications ( https://www.lua.org/manual/5.4/manual.html#lua_Reader ) it should be a `size_t*`, but in this library it's not a pointer.

https://github.com/BindBC/bindbc-lua/blob/master/source/bindbc/lua/v54/types.d#L124

https://github.com/BindBC/bindbc-lua/blob/master/source/bindbc/lua/v53/types.d#L85

Didn't check any of the even older ones.

**Comment by mdparker** [comment]
Fixed in #14.
