### ISSUE TITLE
loadLua() for lua 5.1 and 5.2 use incorrect array size on Linux

### ISSUE THREAD

**Issue by vultraz168** [BindBC/bindbc-lua#4]
https://github.com/BindBC/bindbc-lua/blob/d30dd8f7383f3abdddaf237c871e0af228737528/source/bindbc/lua/v51/binddynamic.d#L312
https://github.com/BindBC/bindbc-lua/blob/d30dd8f7383f3abdddaf237c871e0af228737528/source/bindbc/lua/v51/binddynamic.d#L312

**Comment by mdparker** [comment]
Thanks. Fixed in 0.1.4.
