### ISSUE TITLE
lua_checklong lua_optlong typo in v53

### ISSUE THREAD

**Issue by kraybit** [BindBC/bindbc-lua#5]
- In [source/bindbc/lua/v53/package.d, line 140](https://github.com/BindBC/bindbc-lua/blob/672ec02cc7deca84bfceb6d025e03d5a4e79802a/source/bindbc/lua/v53/package.d#L140)
- `lua_checklong` is declared twice — both with the wrong parameters
- `lua_optlong` is missing

---
Trivia
- DMD doesn't catch this error
- LDC2 does

**Comment by mdparker** [comment]
Thanks! I'll fix it shortly.

**Comment by mdparker** [comment]
Fixed in 0.2.0.
