### ISSUE TITLE
Error in v54 code

### ISSUE THREAD

**Issue by Dmunch04** [BindBC/bindbc-lua#9]
I get this error whenever I'm trying to using lua 5.4 with bindbc-lua:
```
../../../.dub/packages/bindbc-lua-0.4.0/bindbc-lua/source/bindbc/lua/v54/package.d(323,9): Error: return expression expected
```
Although I think it's something on my end, as it seems there is a return in the source code, but I'm not sure?

**Comment by mdparker** [comment]
It's not you. It's me. That line does have a return expression, but the function it calls for the return value was mistakenly declared with a `void` return in the static binding. The dynamic binding was properly declared to return `int`. I've fixed the static binding and pushed 0.4.1.
